name: PR Notification
on: [pull_request, pull_request_review, pull_request_review_comment]

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    name: Run
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Fire Notification
        uses: Lubycon/github-reviewer-noti-action@v2.1.0
        with:
          github-token: ${{ secrets.LUBYCON_GITHUB_TOKEN }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel-id: ${{ secrets.SLACK_CHANNEL_ID }}