name: Publish Typodoc

on:
  push:
    branches:
      - main

jobs:
  typodoc-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Set Git Configulations
        run: |
          git config --global user.email "lubycon@gmail.com"
          git config --global user.name "lubycon"
        env:
          GHty_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Validate dependencies
        run: yarn install --immutable --immutable-cache
      - name: Build
        run: yarn build:all
      - name: Test
        run: yarn test:all
      - name: Build Typedoc
        run: yarn docs:generate
      - name: Publish
        run: yarn docs:deploy
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        